version: 0.2

phases:
  pre_build:
    commands:
      - echo "Instalando kubectl (match do minor do cluster)"
      - |
        K8S_MINOR=$(aws eks describe-cluster --name "${EKS_CLUSTER_NAME}" --region "${AWS_DEFAULT_REGION}" --query 'cluster.version' --output text | cut -d. -f1-2)
        KUBECTL_VER=$(curl -sSfL "https://dl.k8s.io/release/stable-${K8S_MINOR}.txt")
        echo "Baixando kubectl ${KUBECTL_VER}"
        curl -sSfL -o kubectl "https://dl.k8s.io/${KUBECTL_VER}/bin/linux/amd64/kubectl"
        install -m 0755 kubectl /usr/local/bin/kubectl
      - echo "Configurando kubeconfig"
      - aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region "${AWS_DEFAULT_REGION}"
  build:
    commands:
      - echo "Aplicando manifests"
      - kubectl apply -f dist/k8s/deployment.yaml
      - kubectl apply -f dist/k8s/service.yaml
      - echo "Aguardando rollout"
      - kubectl rollout status deploy/frontend --timeout=180s
  post_build:
    commands:
      - kubectl get deploy,pods,svc -o wide

artifacts:
  files:
    - dist/imageDetail.json
